### This tutorial tests field_subsample method given in hcipy.

#### Makesure hcipy is already installed in your conda env

In [2]:
import numpy as np
import hcipy

#### Simple numpy functions to bin pixels in a 2d array

In [8]:
def matrix_subsample(matrix, n, m):
    """
    Returns a downsampled-matrix with reduced order.
    
    Parameters 
    ----------
    matrix : numpy 2D array
        The original matrix which we want to reduce/ subsample.
    n : int
        number of rows of the reduced matrix
    m : int
        number of coloumns of the reduced matrix
    
    Returns
    -------
     matrix_reduced : numpy 2D array
         The downsampled matrix of shape (n,m)
    """
    arr_sum = []
    l = matrix.shape[0]//n  # block length
    b = matrix.shape[1]//m  # block breadth
    for i in range(n):
        for j in range(m):
            sum_pixels = np.sum(matrix[i*l: (i+1)*l, j*b: (j+1)*b])
            arr_sum.append(sum_pixels)
    matrix_reduced = np.reshape(np.array(arr_sum), (n, m))
    
    return matrix_reduced

def matrix_subsample_fast(matrix, n, m):
    """
    Returns a downsampled-matrix with reduced order.
    
    Parameters 
    ----------
    matrix : numpy 2D array
        The original matrix which we want to reduce/ subsample.
    n : int
        number of rows of the reduced matrix
    m : int
        number of coloumns of the reduced matrix
    
    Returns
    -------
     matrix_reduced : numpy 2D array
         The downsampled matrix of shape (n,m)
    """
    l = matrix.shape[0] // n  # block length
    b = matrix.shape[1] // m  # block breadth
    new_shape = (n, l, m, b)
    reshaped_array = matrix.reshape(new_shape)
    matrix_reduced = np.sum(reshaped_array, axis=(1, 3))
    
    return matrix_reduced

#### Check the ouput you get from matrix_subsample

In [12]:
a = np.ones((4,4))
a_downsampled = matrix_subsample(a,2,2)
print(a,'\n', a_downsampled)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[4. 4.]
 [4. 4.]]


#### Use hcipy method to test the same result.